server:
  port: 8090

spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: consumerGroup1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      bootstrap-servers: localhost:9092
      client-id: clientId1
      enable-auto-commit : false
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
